#!/usr/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOMEDIR=$(eval echo "~`whoami`")

if [ ! -z $SECURE_FILES ]; then
    # have to use  us-east-1 - aws tool does not recognize anything else
    # for S3 download
    sudo docker run --rm \
        -v ${HOMEDIR}:/data/ behance/docker-aws-s3-downloader \
         us-east-1 $CONTROL_TIER_S3SECURE_BUCKET $SECURE_FILES

    # must chown all files to core for use
    FILES=(${SECURE_FILES//:/ })
    for file in "${FILES[@]}"; do
        PIECES=(${file//,/ })
        S3FILE=${PIECES[0]}
        PERMS=${PIECES[1]}
        TARGET=${PIECES[2]}

        if [ "${TARGET}" == "" ]; then
            TARGET="${S3FILE}"
        fi

        sudo chown -R `whoami`:`whoami` ${HOMEDIR}/${TARGET}
    done
fi

# ensure that we have a public key for our RSA key and that it's authorized
if [ -f /home/`whoami`/.ssh/id_rsa ]; then
    ssh-keygen -f /home/`whoami`/.ssh/id_rsa -y > /home/`whoami`/.ssh/id_rsa.pub
    cat /home/`whoami`/.ssh/id_rsa.pub >> /home/`whoami`/.ssh/authorized_keys
fi

# ignore requests against github.com
# TODO: maybe...re-evaluate this
echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ${HOMEDIR}/.ssh/config

if [ ! -d /etc/profile.d ]; then
    sudo mkdir /etc/profile.d
fi
sudo cp ${SCRIPTDIR}/v2/profile.d/* /etc/profile.d/.

if [ -f /etc/environment ]; then
    source /etc/environment
fi

if [ "${NODE_ROLE}" != "control" ]; then
    sudo cp ${SCRIPTDIR}/v2/non-control-profile.d/* /etc/profile.d/.
fi

for script in $(ls ${SCRIPTDIR}/v2/setup)
do
    sudo /bin/bash ${SCRIPTDIR}/v2/setup/${script}
done

for unit in $(ls ${SCRIPTDIR}/v2/fleet)
do
    sudo fleetctl submit ${SCRIPTDIR}/v2/fleet/${unit}
    sudo fleetctl start ${SCRIPTDIR}/v2/fleet/${unit}
done
